# Generated by Django 4.0.3 on 2022-10-30 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('place_of_born', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('date_release', models.DateTimeField()),
                ('running_time', models.IntegerField()),
                ('country', models.CharField(max_length=120)),
                ('production_company', models.TextField(max_length=200)),
                ('detail', models.TextField()),
                ('character', models.ManyToManyField(to='api_star_wars.character')),
                ('director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_star_wars.director')),
                ('productor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_star_wars.productor')),
            ],
        ),
    ]
