# Generated by Django 4.0.3 on 2022-10-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_star_wars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='character',
            new_name='characters',
        ),
        migrations.AddField(
            model_name='movie',
            name='planets',
            field=models.ManyToManyField(to='api_star_wars.planet'),
        ),
    ]
