# Generated by Django 4.0.3 on 2022-11-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_star_wars', '0002_planet_rename_character_movie_characters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='api_star_wars.movie'),
        ),
    ]
